### PR TITLE
Add data type classes

### PR DESCRIPTION
**Pull request by zultron**
This PR adds a base data type class and subclasses for CiA 301 and EtherCAT CoE device data types.

CAN CiA 301 devices, and EtherCAT CoE devices based on those, have dictionaries of objects with basic data types.  The basic data types are the same, e.g. bit, signed/unsigned int, float and string types.  CiA 301 devices appear to name the types according to the tastes of the device developer (correct me if I'm wrong!), whereas EtherCAT standardizes the names in ETG.2000.

The base data type class here provides generic, common names for the data types, e.g. `uint16`, and accessors for use by device-independent code.  The device-specific subclasses provide specific names, e.g. `UNSIGNED16` (CAN) or `UINT` (ECAT), and accessors for use by code such as the EtherCAT ESI file parser.

Data types carry their own information about bit length and signedness, how to convert back and forth between `str` and Python types.  Code may use this for e.g. reading and writing SDOs or configuring PDOs, and differences between the data types and differences between CAN and EtherCAT are made transparent.

### CODE REVIEW

**Comment by facontidavide** [comment]
Hi,

some feedback that may be is not 100% relevant, since I am not very good at  Python. So bear with me ;) 

The way I usually implemented this in the past was making the type enum and getting the properties like this:

(remember, I am not super familiar with python)

```python
from enum import IntEnum

class DataType(IntEnum):
    INT8 = 0
    INT16 = 1
    INT32 = 2
    UINT8= 3
    UINT16= 4
    UINT32 = 5
    FLOAT= 6
    STR = 7

num_bits=[8, 16, 32, 8, 16, 32, 32, None]
shared_name = ["int8", "int16", "int32", "uint8", "uint16", "uint32", "float", "str"]

# to be used as
num_bits[DataType.INT8]
```
I miss the point of subclasses. I am not saying it will not work, just seems more verbose

**Comment by zultron** [comment]
Python's `enum` module is really handy.  I use it pretty often, too.

> I miss the point of subclasses. I am not saying it will not work, just seems more verbose

It's a lot of messy apparatus in that base class, isn't it?  It's also hard to explain; you can see my poor first attempt in the base class's [doc string][1].  Let's see if I can do any better here.

-----

This software project ties together a set of targeted software
components for the purpose of managing a set of targeted hardware
devices.  A basic thing those software and hardware components share
in common are ten or so basic data types; this is the subject of this
PR.

Each one of these several shared data types has a few basic attributes
and methods, no matter where it is used:  bit length, base Python
type, string conversion methods, etc.  But each different software and
hardware component has its own special requirements needing special
support from data types, such as special identifiers, string formatter
methods, etc.  In addition, we also want the flexibility to swap
hardware and software components in and out, depending on the
application.

CAN or EtherCAT device?  CANopenNode, or IgH or SOEM EtherCAT master?
HAL or custom hardware interface?  So many possible combinations, each
multiplied by ten data types.  How can we cover all that in our
implementation without writing a whole ton of spaghetti?  My strategy
is to encapsulate each component's differences in a (data-only, where
possible) subclass, enable arbitrary combinations of components
with multiple inheritance ("diamond" inheritance using Python3's C3
MRO), and automatically generate concrete data type subclasses
(`int32` et al.).  That is, don't write spaghetti; instead, build a
spaghetti factory!

To give you an idea how it works, here are three concrete examples of
data type subclasses for specific components.  Each of these subclasses
is implemented in <2doz. well-spaced LOC!

#### 1. EtherCAT ETG.2000:
  - The `src/hw_device_mgr/ethercat/data_types.py` module does the
   following:
    - Define a new `EtherCATDataType` base class
    - Subclass of the base `DataType` class
    - Define values for data type subclass `name` attributes
  - The spaghetti factory then transparently generates data type subclasses:
    - E.g. `EtherCATInt32Type` for `int32`
    - Two parents, e.g. `EtherCATDataType` and `Int32Type` classes for `int32`
    - Adds `name` class attribute, e.g. `name="DINT"` for `int32`
    - Indexes subclass; e.g. for `int32`:
      - `EtherCATDataType.by_name("DINT")` -> `EtherCATInt32Type` class
      - `EtherCATDataType.int32` -> `EtherCATInt32Type` class
    - As parent class, passes attrs & methods, e.g. value <-> string conversion
  - Usage:  ESI XML file: `<Type>DINT</Type>`,
    `EtherCATDataType.by_name("DINT")` -> `EtherCATInt32Type`

#### 2.  HAL component "pins":
  - The `src/hw_device_mgr/hal/data_types.py` module (in a near-future
    PR) does the following:
    - Define a new `HALDataType` base class
    - Subclass of the base `DataType` class; HAL-related stuff from
      `HALMixin` class
    - Define values for data type subclass `hal_type` attributes
    - Add a `hal_type` int -> string conversion method
  - The spaghetti factory then transparently generates data type subclasses:
    - E.g. `HALInt32Type` for `int32`
    - Two parents, e.g. `HALDataType` and `Int32Type` classes for `int32`
    - Adds `hal_type` class attribute, e.g. `hal_type="hal.HAL_S32"` for `int32`
      - `HALDataType.int32` -> `HALInt32Type` class
    - Indexes subclass; e.g. for `int32`:
      - `HALDataType.int32` -> `HALInt32Type` class
    - Etc.
  - Usage:  Create a HAL pin:  `hal_comp.newpin(pin_name, data_type->hal_type, pin_dir)`

#### 3.  `lcec` HAL EtherCAT driver:  **Dual inheritance!**
  - The `src/hw_device_mgr/lcec/data_types.py` module (in a near-future
    PR) does the following:
    - Define a new `LCECDataType` base class
    - **Two** parents:  `EtherCATDataType` and `HALDataType`
    - Define values for data type subclass `igh_type` attributes
  - The spaghetti factory then transparently generates data type subclasses:
    - E.g. `LCECInt32Type` for `int32`
    - **Three** parents, e.g. `LCECDataType`, `EtherCATInt32Type` and
      `HALInt32Type` classes for `int32`
    - Adds `igh_type` class attribute, e.g. `igh_type="int32"` for `int32`
    - Indexes subclass; e.g. for `int32`:
      - `LCECDataType.by_name("DINT")` -> `LCECInt32Type` class
      - `LCECDataType.int32` -> `LCECInt32Type` class
    - Etc.
  - Usages:
    - Write a drive param:  `f"ethercat upload [...] --type {data_type->igh_type}"`
    - Also inherit usages from parents see above "ESI XML file" and
      "Create a HAL pin" examples

In this last example, note the multiple inheritance:  the HAL `lcec`
component is a driver for the IgH EtherCAT master, so the
`LCECDataType` class inherits from both HAL and EtherCAT classes.  As
such, an EtherCAT device object (near-future PR!) can use this single
`DataType` subclass
- when reading its ESI device description file,
- when updating drive parameters with the IgH `ethercat` utility,
- when generating the XML configuration for the `lcec` component, and
- when creating control and status word HAL pins for
  enabling/disabling the drive in the `hw_device_mgr` ROS node.

I hope this last example shows off the power this subclass factory
scheme conveys.  The device classes (near-future PRs) also use such
schemes to simplify and encapsulate additional functionality, although
of course stuffing some of the mess down into the base class!

[1]:  https://github.com/tormach/hw_device_mgr/pull/4/commits/11c571243375b2c066cc9c71960c3caed828572f#diff-fc88f46db7ce5650b36b2c75d0caffd9b1b2b7f98986c5908b28497d0704d1ceR7-R44

**Comment by facontidavide** [comment]
ok, don't wait for me to merge this. Go ahead

**Comment by zultron** [comment]
Superseded by #5 .

**Pull request closed without merging**
