### PR TITLE
Add sim mode

### PR DESCRIPTION
**Pull request by zultron**
This PR goes on top of #8.

This PR moves the simulated devices out of the unit tests and into usable device classes.  Sim configurations can now include sim CiA 301 and 402 devices that pretend to step through their respective state machines, and changes to the device manager may be tested against actual application code without needing real hardware.

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
I did an initial pass on this PR, but I would prefer to drop the official review after #8 gets merged.

**Comment by zultron** [comment]
Rebased on #8 after its merge.  Thank you @vatanaksoytezer for that review!

Tests all green.  Ready for review!

**Comment by zultron** [comment]
Sim mode broke real hardware mode, and I have fixes in progress.  Changed back to draft status for now.

**Comment by zultron** [comment]
Superseded by #12.

**Pull request closed without merging**
